export default {
  login: "ClaksHDS",
  id: 95137350,
  node_id: "U_kgDOBauuRg",
  avatar_url: "https://avatars.githubusercontent.com/u/95137350?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ClaksHDS",
  html_url: "https://github.com/ClaksHDS",
  followers_url: "https://api.github.com/users/ClaksHDS/followers",
  following_url: "https://api.github.com/users/ClaksHDS/following{/other_user}",
  gists_url: "https://api.github.com/users/ClaksHDS/gists{/gist_id}",
  starred_url: "https://api.github.com/users/ClaksHDS/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ClaksHDS/subscriptions",
  organizations_url: "https://api.github.com/users/ClaksHDS/orgs",
  repos_url: "https://api.github.com/users/ClaksHDS/repos",
  events_url: "https://api.github.com/users/ClaksHDS/events{/privacy}",
  received_events_url: "https://api.github.com/users/ClaksHDS/received_events",
  type: "User",
  site_admin: false,
  name: "Claks",
  company: null,
  blog: "",
  location: "Bristol, UK",
  email: null,
  hireable: null,
  bio: "I code things",
  twitter_username: null,
  public_repos: 6,
  public_gists: 0,
  followers: 0,
  following: 4,
  created_at: "2021-11-27T15:13:08Z",
  updated_at: "2022-08-31T13:21:17Z",
};
